name: suite_spot
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  firebase_core:
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  cached_network_image: ^3.2.3
  flutter_dotenv: ^5.2.1
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Italiana-Regular
      fonts:
        - asset: assets/fonts/Italiana-Regular.ttf